config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matteogrisenti/Deliveroo-Plugin:
      branch: master
      repo: https://github.com/matteogrisenti/Deliveroo-Plugin.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-alizarin-squirt.sh
        container: qc.acc_jumpy-ruby-uakari
  QC.Doc:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-chocolate-armadillo.sh
        container: qc.doc_whiny-cinnamon-quail
      github.com/matteogrisenti/Deliveroo-Plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-grey-lionfish.sh
        container: qc.doc_cheeky-copper-spitz
      github.com/matteogrisenti/Deliveroo-Plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lilac-goose.sh
        container: qc.doc_gloppy-sangria-magpie
  QC.Lic:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-mustard-weasel.sh
        container: qc.lic_muzzy-mustard-dalmatian
  QC.Sty:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-platinum-akbash.sh
        container: qc.sty_shaky-carmine-zebra
      github.com/matteogrisenti/Deliveroo-Plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cerulean-echidna.sh
        container: qc.sty_homely-teal-eleuth
  QC.Ver:
    repos:
      github.com/matteogrisenti/Deliveroo-Plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ivory-bulldog.sh
        container: qc.ver_sickly-myrtle-akbash
timeout: 5400
